background_opacity 0.6

font_family Terminess Nerd Font


cursor #d65d6e
# Cursor shape
cursor_shape beam        

# Make it blink
cursor_blink_interval 0.5

# Stop blinking after 15 seconds (0 = blink forever)
cursor_stop_blinking_after 15.0

# Cursor trail animation
cursor_trail 3

# Smooth cursor movement
shell_integration enabled
